AWSTemplateFormatVersion: '2010-09-09'
Description: "2-tier app with Web EC2 and RDS MySQL"

Parameters:
  PublicSubnetId:
    Type: String
  PrivateSubnetId:
    Type: String
  WebSGId:
    Type: String
  DBSGId:
    Type: String
  KeyName:
    Type: String
    Description: Name of EC2 Key Pair

Resources:
  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      ImageId: ami-0f8ca728008ff5af4  # Ubuntu ap-south-1
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: !Ref PublicSubnetId
          GroupSet: [!Ref WebSGId]

  MyDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: MyDatabase
      AllocatedStorage: 20
      DBInstanceClass: db.t2.micro
      Engine: MySQL
      EngineVersion: "8.0"
      MasterUsername: admin
      MasterUserPassword: Admin12345
      VPCSecurityGroups: [!Ref DBSGId]
      DBSubnetGroupName:
        Ref: MyDBSubnetGroup
      PubliclyAccessible: false

  MyDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Private subnets for RDS"
      SubnetIds: [!Ref PrivateSubnetId]
      DBSubnetGroupName: "my-db-subnet-group"

Outputs:
  WebServerPublicIP:
    Value: !GetAtt WebServer.PublicIp
  RDSInstanceEndpoint:
    Value: !GetAtt MyDB.Endpoint.Address
