AWSTemplateFormatVersion: '2010-09-09'
Description: "Security groups for Web and DB tier"

Parameters:
  VPCId:
    Type: String
  WebPort:
    Type: Number
    Default: 80
  DBPort:
    Type: Number
    Default: 3306

Resources:
  WebSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP access
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref WebPort
          ToPort: !Ref WebPort
          CidrIp: 0.0.0.0/0

  DBSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow MySQL access from Web
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref DBPort
          ToPort: !Ref DBPort
          SourceSecurityGroupId: !Ref WebSG

Outputs:
  WebSGId:
    Value: !Ref WebSG
  DBSGId:
    Value: !Ref DBSG
